### ISSUE TITLE
OpenEVSE with battery don't detect power loss

### ISSUE THREAD

**Issue by DylanVautrin** [lincomatic/open_evse#169]
Hello,
I'm working on a project using OpenEVSE and a battery, basically, I have an issue for a special case of power loss.
When I lose the power for the T2 plug, my board is still powered by the battery, and I don't detect anything for this case.
If I'm in a session, and I have a power loss, the Atmega detect it, cut the session and send an error "GroundFailure" to the ESP, but the error is "erase" since the session is ended, so the last status I got is "Available".
And if I'm not in a session, it didn't detect it at all. I measured the value on the optocoupler (AC_TEST and AC_TEST_2) (the one that manage the test for the relay) and the value that is sent to the Atmega don't change in both case.
Someone have an idea to detect this kind of power loss without making any hardware modification ?
Thanks

**Comment by lincomatic** [comment]
The only way I can think of to do what you want is to close the contactor and test for voltage at an AC test pin. If no voltage is detected, then there's no AC power. But this isn't advised because 1) the same condition is used to detect a fault and 2) it's not a good idea to close the contactor at any random time, because of the shock hazard
