### ISSUE TITLE
Testing for supported features

### ISSUE THREAD

**Issue by jeremypoulter** [lincomatic/open_evse#70]
I have just been testing the fix for #69 and it is protected by TEMPERATURE_MONITORING_NY which I will raise separately, however this raises a larger question of what is the best way to check if the firmware supports particular features? Just trial and error or is there something more explicit?

**Comment by lincomatic** [comment]
Sorry, currently, there's no way to know what commands are enabled. For a while I tried to do that via RAPI version, but there are so many #ifdef's for EVSE features that checking RAPI version wouldn't work, anyway. You have to just test a RAPI command and see if it's accepted. 

Speaking of  #69, yikes, I really blew that one! I've had very little time to work on it lately, and I neglected to test the code, since it looked so straightforward. I'm going to reopen the issue
