### ISSUE TITLE
Energy Limit: additive rather than cumulative 

### ISSUE THREAD

**Issue by glynhudson** [lincomatic/open_evse#96]
Currently, the energy limit is added onto the current elapsed energy e.g. if an EV has charged to 5kWh and then user applies an Energy Limit of 6kWh the charge will not stop until the elapsed energy has reached 11kWh. 

I think a more consistent user experience would be for the charge to stop when the elapsed energy reaches the energy limit e.g. 6kWh in the above example. What are your thoughts on this?

I've tried to illustrate with a video, sorry it's a bit of a ramble: 
https://photos.app.goo.gl/CYVaFccno2mLa4ih9

**Comment by lincomatic** [comment]
Sorry, I didn't see this until just now. Actually, the charge & time limits were designed to extend the current session, rather than be absolute limits, as is documented in rapi_proc.h:

SH kWh - set cHarge limit to kWh
 NOTES:
  - allowed only when EV connected in State B or C
  - temporarily disables delay timer until EV disconnected or limit reached
  - actually *extends* the charge to the limit. So say, current session has
    already charged 10kWh, $SH 5 will charge until 15kWh

The thinking at the time was my typical usage.. I would walk up to the car after it'd been plugged in a while, see how charged the car was from its own internal gauge, and then decide how many more kWh I needed in order to make my trip.

But I can understand how a typical user could think of it as a hard limit rather than an extension.
Therefore, I've changed both charge & time limit to your liking in v5.1.0

**Comment by glynhudson** [comment]
Sorry for the slow reply. Thanks a lot for the change, a number of users had also mentioned this to us. I think the limits are more intuitive now. I've just tested the changes and the limits now work great. Thanks again 👍
